# Generated by Django 5.2.8 on 2025-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mas_vendido',
            field=models.BooleanField(default=False),
        ),
    ]
