# Generated by Django 5.2.8 on 2025-11-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
