# Generated by Django 5.2.8 on 2025-11-29 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_pedido_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='no definida', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En Camino'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=150),
        ),
    ]
