# Generated by Django 5.2.8 on 2026-05-11 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_pedido_ciudad_pedido_direccion_pedido_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='firma',
            field=models.TextField(blank=True, help_text='Datos de la firma en formato Base64', null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_entrega', to='web.pedido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
