# Generated by Django 5.2.8 on 2026-05-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_entrega_firma_entrega_foto_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('comentario', models.TextField(max_length=300, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=False, verbose_name='Aprobado (Se muestra en la web)')),
                ('destacado_inicio', models.BooleanField(default=False, verbose_name='Mostrar en Carrusel de Inicio')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
