# Generated by Django 5.2.8 on 2026-05-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_testimonio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa/galeria/')),
                ('video', models.FileField(blank=True, null=True, upload_to='empresa/galeria/videos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galería Empresa',
                'verbose_name_plural': 'Galería Empresa',
            },
        ),
        migrations.CreateModel(
            name='InformacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titulo', models.CharField(max_length=200)),
                ('hero_descripcion', models.TextField()),
                ('hero_imagen', models.ImageField(blank=True, null=True, upload_to='empresa/banner/')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='empresa/videos/')),
                ('historia_titulo', models.CharField(max_length=200)),
                ('historia_descripcion', models.TextField()),
                ('historia_imagen', models.ImageField(blank=True, null=True, upload_to='empresa/historia/')),
                ('trabajo_titulo', models.CharField(max_length=200)),
                ('trabajo_descripcion', models.TextField()),
                ('trabajo_video', models.FileField(blank=True, null=True, upload_to='empresa/trabajo/')),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('objetivo', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Información Empresa',
                'verbose_name_plural': 'Información Empresa',
            },
        ),
    ]
