# Generated by Django 5.2.8 on 2026-05-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_galeriaempresa_informacionempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaempresa',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informacionempresa',
            name='hero_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Video YouTube'),
        ),
        migrations.AddField(
            model_name='informacionempresa',
            name='trabajo_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Video Trabajo'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='firma',
            field=models.TextField(blank=True, help_text='Firma en Base64', null=True),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='hero_descripcion',
            field=models.TextField(verbose_name='Descripción Principal'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='hero_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/banner/', verbose_name='Imagen Banner'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='hero_titulo',
            field=models.CharField(max_length=200, verbose_name='Título Principal'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='empresa/videos/', verbose_name='Video Subido'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='historia_descripcion',
            field=models.TextField(verbose_name='Descripción Historia'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='historia_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/historia/', verbose_name='Imagen Historia'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='historia_titulo',
            field=models.CharField(max_length=200, verbose_name='Título Historia'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='mision',
            field=models.TextField(verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='trabajo_descripcion',
            field=models.TextField(verbose_name='Descripción Cómo Trabajamos'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='trabajo_titulo',
            field=models.CharField(max_length=200, verbose_name='Título Cómo Trabajamos'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='trabajo_video',
            field=models.FileField(blank=True, null=True, upload_to='empresa/trabajo/', verbose_name='Video Trabajo'),
        ),
        migrations.AlterField(
            model_name='informacionempresa',
            name='vision',
            field=models.TextField(verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='destacado_inicio',
            field=models.BooleanField(default=False, verbose_name='Mostrar en inicio'),
        ),
    ]
